name: Check Camping Price

on:
  schedule:
    - cron: '42 6 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le code du dépôt
      uses: actions/checkout@v4

    - name: Installer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Installer les dépendances
      run: |
        pip install requests playwright
        playwright install chromium

    - name: Executer le script de vérification
      run: python camping.py
